### ISSUE TITLE
Issue in install python3 -m pip install -r requirements/dev.txt

### ISSUE THREAD

**Issue by ssultan1** [laramies/theHarvester#429] opened 2020-05-11 01:03 UTC
Hello
I am facing issue when i run 
python3 -m pip install -r requirements/dev.txt
Output is 
![Screenshot_20200511_025941_com termux](https://user-images.githubusercontent.com/63744161/81515363-ee5e6400-9333-11ea-94cf-9554c2d722fc.jpg)
Would you please tell me where the error?

Thanks for support

**Comment by L1ghtn1ng** [comment] 2020-05-11 01:28
it is due to flake8 needing a less higher version of pyflakes even though I can confirm all is well with that version. Just remove pyflakes from the dev.txt and the correct version will be installed. There is an alpha release of flake8 that hopefully will go GA which will allow this version.
________________________________

**Comment by ssultan1** [comment] 2020-05-11 21:41
Thanks for your fast response
But i think facing another issue as below screen
![Screenshot_20200511_233904_com termux](https://user-images.githubusercontent.com/63744161/81614749-c6790a00-93e0-11ea-9693-05905558572e.jpg)


> Hello
> I am facing issue when i run
> python3 -m pip install -r requirements/dev.txt
> Output is
> ![Screenshot_20200511_025941_com termux](https://user-images.githubusercontent.com/63744161/81515363-ee5e6400-9333-11ea-94cf-9554c2d722fc.jpg)
> Would you please tell me where the error?
> 
> Thanks for support

**Comment by NotoriousRebel** [comment] 2020-05-12 03:44
Please output the error information as text and if you google it you will most likely find the solution: perhaps try ```sudo apt-get install python3-dev```

**Comment by L1ghtn1ng** [comment] 2020-05-12 20:26
The flake8 issue should now be fixed in master but from what I can tell are you running this on nethunter if so not sure how well that will work but please do try what @NotoriousRebel  says

**Comment by ssultan1** [comment] 2020-05-12 23:09
> Please output the error information as text and if you google it you will most likely find the solution: perhaps try `sudo apt-get install python3-dev`

Hello would you please checkout below output
$ python3 -m pip install -r requirements.txt
Requirement already satisfied: aiodns==2.0.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 1)) (2.0.0)
Requirement already satisfied: aiohttp==3.6.2 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 2)) (3.6.2)
Requirement already satisfied: aiosqlite==0.13.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 3)) (0.13.0)
Requirement already satisfied: beautifulsoup4==4.9.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 4)) (4.9.0)
Requirement already satisfied: dnspython==1.16.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 5)) (1.16.0)
Requirement already satisfied: netaddr==0.7.19 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 6)) (0.7.19)
Requirement already satisfied: plotly==4.7.1 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 7)) (4.7.1)
Requirement already satisfied: PyYAML==5.3.1 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 8)) (5.3.1)
Requirement already satisfied: requests==2.23.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 9)) (2.23.0)
Requirement already satisfied: retrying==1.3.3 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 10)) (1.3.3)
Requirement already satisfied: shodan==1.23.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 11)) (1.23.0)
Requirement already satisfied: texttable==1.6.2 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 12)) (1.6.2)
Requirement already satisfied: lxml==4.5.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 13)) (4.5.0)
Collecting uvloop==0.14.0
  Using cached uvloop-0.14.0.tar.gz (2.0 MB)
Requirement already satisfied: certifi==2020.4.5.1 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from -r requirements/base.txt (line 15)) (2020.4.5.1)
Requirement already satisfied: pycares>=3.0.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from aiodns==2.0.0->-r requirements/base.txt (line 1)) (3.1.1)
Requirement already satisfied: attrs>=17.3.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from aiohttp==3.6.2->-r requirements/base.txt (line 2)) (19.3.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from aiohttp==3.6.2->-r requirements/base.txt (line 2)) (3.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from aiohttp==3.6.2->-r requirements/base.txt (line 2)) (1.4.2)
Requirement already satisfied: multidict<5.0,>=4.5 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from aiohttp==3.6.2->-r requirements/base.txt (line 2)) (4.7.5)
Requirement already satisfied: chardet<4.0,>=2.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from aiohttp==3.6.2->-r requirements/base.txt (line 2)) (3.0.4)
Requirement already satisfied: soupsieve>1.2 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from beautifulsoup4==4.9.0->-r requirements/base.txt (line 4)) (2.0)
Requirement already satisfied: six in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from plotly==4.7.1->-r requirements/base.txt (line 7)) (1.14.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from requests==2.23.0->-r requirements/base.txt (line 9)) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from requests==2.23.0->-r requirements/base.txt (line 9)) (2.9)
Requirement already satisfied: click in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from shodan==1.23.0->-r requirements/base.txt (line 11)) (7.1.2)
Requirement already satisfied: click-plugins in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from shodan==1.23.0->-r requirements/base.txt (line 11)) (1.1.1)
Requirement already satisfied: colorama in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from shodan==1.23.0->-r requirements/base.txt (line 11)) (0.4.3)
Requirement already satisfied: XlsxWriter in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from shodan==1.23.0->-r requirements/base.txt (line 11)) (1.2.8)
Requirement already satisfied: cffi>=1.5.0 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from pycares>=3.0.0->aiodns==2.0.0->-r requirements/base.txt (line 1)) (1.14.0)
Requirement already satisfied: pycparser in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from cffi>=1.5.0->pycares>=3.0.0->aiodns==2.0.0->-r requirements/base.txt (line 1)) (2.20)
Could not build wheels for aiodns, since package 'wheel' is not installed.
Could not build wheels for aiohttp, since package 'wheel' is not installed.
Could not build wheels for aiosqlite, since package 'wheel' is not installed.
Could not build wheels for beautifulsoup4, since package 'wheel' is not installed.
Could not build wheels for dnspython, since package 'wheel' is not installed.
Could not build wheels for netaddr, since package 'wheel' is not installed.
Could not build wheels for plotly, since package 'wheel' is not installed.
Could not build wheels for PyYAML, since package 'wheel' is not installed.
Could not build wheels for requests, since package 'wheel' is not installed.
Could not build wheels for retrying, since package 'wheel' is not installed.
Could not build wheels for shodan, since package 'wheel' is not installed.
Could not build wheels for texttable, since package 'wheel' is not installed.
Could not build wheels for lxml, since package 'wheel' is not installed.
Could not build wheels for uvloop, since package 'wheel' is not installed.
Could not build wheels for certifi, since package 'wheel' is not installed.
Could not build wheels for pycares, since package 'wheel' is not installed.
Could not build wheels for attrs, since package 'wheel' is not installed.
Could not build wheels for async-timeout, since package 'wheel' is not installed.
Could not build wheels for yarl, since package 'wheel' is not installed.
Could not build wheels for multidict, since package 'wheel' is not installed.
Could not build wheels for chardet, since package 'wheel' is not installed.
Could not build wheels for soupsieve, since package 'wheel' is not installed.
Could not build wheels for six, since package 'wheel' is not installed.
Could not build wheels for urllib3, since package 'wheel' is not installed.
Could not build wheels for idna, since package 'wheel' is not installed.
Could not build wheels for click, since package 'wheel' is not installed.
Could not build wheels for click-plugins, since package 'wheel' is not installed.
Could not build wheels for colorama, since package 'wheel' is not installed.
Could not build wheels for XlsxWriter, since package 'wheel' is not installed.
Could not build wheels for cffi, since package 'wheel' is not installed.
Could not build wheels for pycparser, since package 'wheel' is not installed.
Installing collected packages: uvloop
    Running setup.py install for uvloop ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-iy0k1okx/uvloop/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-iy0k1okx/uvloop/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-h63f058t/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.8/uvloop
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-iy0k1okx/uvloop/
    Complete output (182 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.8
    creating build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/__init__.py -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/_patch.py -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/_testbase.py -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/_noop.py -> build/lib.linux-aarch64-3.8/uvloop
    running egg_info
    writing uvloop.egg-info/PKG-INFO
    writing dependency_links to uvloop.egg-info/dependency_links.txt
    writing top-level names to uvloop.egg-info/top_level.txt
    reading manifest file 'uvloop.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/.git'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/docs'
    warning: no previously-included files matching '*' found under directory 'vendor/libuv/img'
    writing manifest file 'uvloop.egg-info/SOURCES.txt'
    copying uvloop/cbhandles.pxd -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/cbhandles.pyx -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/dns.pyx -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/errors.pyx -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/loop.c -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/loop.pxd -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/loop.pyx -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/lru.pyx -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/pseudosock.pyx -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/request.pxd -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/request.pyx -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/server.pxd -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/server.pyx -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/sslproto.pxd -> build/lib.linux-aarch64-3.8/uvloop
    copying uvloop/sslproto.pyx -> build/lib.linux-aarch64-3.8/uvloop
    creating build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/async_.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/async_.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/basetransport.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/basetransport.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/check.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/check.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/handle.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/handle.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/idle.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/idle.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/pipe.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/pipe.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/poll.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/poll.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/process.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/process.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/stream.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/stream.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/streamserver.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/streamserver.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/tcp.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/tcp.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/timer.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/timer.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/udp.pxd -> build/lib.linux-aarch64-3.8/uvloop/handles
    copying uvloop/handles/udp.pyx -> build/lib.linux-aarch64-3.8/uvloop/handles
    creating build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/__init__.py -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/compat.h -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/consts.pxi -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/debug.h -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/debug.pxd -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/flowcontrol.pxd -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/fork_handler.h -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/python.pxd -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/stdlib.pxi -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/system.pxd -> build/lib.linux-aarch64-3.8/uvloop/includes
    copying uvloop/includes/uv.pxd -> build/lib.linux-aarch64-3.8/uvloop/includes
    running build_ext
    checking for a BSD-compatible install... /data/data/com.termux/files/usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /data/data/com.termux/files/usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... no
    checking whether make supports nested variables... no
    checking build system type... aarch64-unknown-linux-gnu
    checking host system type... aarch64-unknown-linux-gnu
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for style of include used by make... none
    checking dependency style of gcc... none
    checking if gcc supports -pedantic flag... yes
    checking for gcc way to treat warnings as errors... -Werror
    checking if gcc supports -fvisibility=hidden... yes
    checking if gcc supports -g flag... yes
    checking if gcc supports -std=gnu89 flag... yes
    checking if gcc supports -Wall flag... yes
    checking if gcc supports -Wextra flag... yes
    checking if gcc supports -Wno-long-long flag... yes
    checking if gcc supports -Wno-unused-parameter flag... yes
    checking if gcc supports -Wstrict-prototypes flag... yes
    checking for ar... ar
    checking the archiver (ar) interface... ar
    checking how to print strings... printf
    checking for a sed that does not truncate output... /data/data/com.termux/files/usr/bin/sed
    checking for grep that handles long lines and -e... /data/data/com.termux/files/usr/bin/grep
    checking for egrep... /data/data/com.termux/files/usr/bin/grep -E
    checking for fgrep... /data/data/com.termux/files/usr/bin/grep -F
    checking for ld used by gcc... /data/data/com.termux/files/usr/bin/aarch64-linux-android-ld
    checking if the linker (/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /data/data/com.termux/files/usr/bin/nm -B
    checking the name lister (/data/data/com.termux/files/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 32768
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... no
    checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /data/data/com.termux/files/usr/bin/aarch64-linux-android-ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /data/data/com.termux/files/usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... yes
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... no
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking whether make supports nested variables... (cached) no
    checking for dlopen in -ldl... yes
    checking for kstat_lookup in -lkstat... no
    checking for gethostbyname in -lnsl... no
    checking for perfstat_cpu in -lperfstat... no
    checking for pthread_mutex_init in -lpthread... yes
    checking for clock_gettime in -lrt... yes
    checking for sendfile in -lsendfile... no
    checking for socket in -lsocket... no
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking sys/ahafs_evProds.h usability... no
    checking sys/ahafs_evProds.h presence... no
    checking for sys/ahafs_evProds.h... no
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating libuv.pc
    config.status: executing depfiles commands
    config.status: executing libtool commands
    error: [Errno 2] No such file or directory: 'make'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-iy0k1okx/uvloop/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-iy0k1okx/uvloop/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-h63f058t/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.8/uvloop Check the logs for full command output.

**Comment by NotoriousRebel** [comment] 2020-05-14 18:59
@ssultan1 could you try this? ```sudo apt-get install build-essential``` then try and install the tool.

**Comment by L1ghtn1ng** [comment] 2020-05-26 21:25
Timeout

**Closed by L1ghtn1ng** 2020-05-26 21:25 UTC
