### ISSUE TITLE
[Feature Request] Specify as argument the location of proxies.yaml or set proxy hardcoded by -p argument

### ISSUE THREAD

**Issue by D3vil0p3r** [laramies/theHarvester#937] opened 2021-12-01 19:22 UTC
**Feature Request**
Setting location of proxies.yaml file as argument. Decouple the presence of proxies.yaml from the `-p` argument since I guess if I specify a proxy by `-p` argument, I don't need of proxies.yaml content (please tell me if this assumption is correct).

**Describe the feature request or bug or other**
Each time, the user is forced to stay in the context of theHarvester folder for executing the tool, because the user needs to stay in the folder containing `proxies.yaml` or this file should be in /etc/theHarvester folder. For example, in case the user just runs:

`theHarvester -d google.com -b all -f ~/output`

we get the error:

    FileNotFoundError: [Errno 2] No such file or directory: 'proxies.yaml'

Furthermore, if the user uses `-p` argument as:

`theHarvester -d google.com -b all -f ~/output -p`

where `-p` allows the tool to use proxies for requests (specified inside proxies.yaml), proxies.yaml file is needed. If I don't use `-p` argument, why the tool is still asking for `proxies.yaml` location?

Summarizing the requests should be:
* Is it possible to make a new argument to specify the path of `proxies.yaml` file?
* Is it possible to use `-p` argument for specifying directly proxies like `socks5://127.0.0.1:9150` instead to use `proxies.yaml` file?
* Is it possible to decouple the need of the presence of `proxies.yaml` file from the absence of `-p` argument?

Thank you

**Comment by L1ghtn1ng** [comment] 2021-12-01 20:49
Even if you do not specify the ```-p```  it checks the locations it expects the file to exist which can be seen in https://github.com/laramies/theHarvester/blob/87e3ed64814e508235fd6a34f61c4ebcf3a91030/theHarvester/lib/core.py#L88-L100 I would say no to your other points as we expect the file to be in a certain structure. I know @NotoriousRebel either is or already added socks support and probably can even add https support now if the lib that we use now supports it. 

Overall it just comes down to the way it was designed. As @NotoriousRebel was the one that added this feature maybe he has some input on this?

**Comment by D3vil0per** [comment] 2021-12-01 21:14
Hello @L1ghtn1ng ,
thank you the answer. I know that the code goes to search on `/etc/theHarvester`. It could be good for Kali Linux user where `theHarvester` directory is already there.
For users of other distros (Debian in my case), that I get the tool by git clone, and place it on a folder like /opt/ or another folder, could be annoying each time run theHarvester staying in that directory. A workaround could be each time change the code above and substituting /etc/ with the actual path, but is not comfortable for standard users.

Furthermore, if the presence of proxies.yaml file should force the entire tool package to have a specific structure, is it not better to not use this proxies.yaml file and use directly the pattern `-p <protocol>://ip:port` (i.e., socks5://127.0.0.1:9150 or http://127.0.0.1:8080 for Burpsuite) as used in other tools?

For the lack of HTTPS support I think that it iis the reason I'm getting an error like the following (for all sources) when I'm using Burpsuite as proxy inside proxies.yaml?

    An exception has occurred: Cannot connect to host www.baidu.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')]

or it is related to the Burp certificate that must be placed in a specific folder?

Let's wait for @NotoriousRebel 

Still thank you!

**Comment by L1ghtn1ng** [comment] 2021-12-01 21:22
The error would be due to you needing to import the burp CA cert into your truststore that should fix that error

**Comment by L1ghtn1ng** [comment] 2021-12-01 21:25
Something that I am going to be working on is packaging up theHarvester as a snap package so directories etc will exist when you install via a snap in the future

**Comment by L1ghtn1ng** [comment] 2021-12-01 21:33
Think this more or less the same issue? #926

**Comment by D3vil0per** [comment] 2021-12-01 21:51
Yes, this issue is the same. I read also the related answer of @NotoriousRebel . It's right that also the api-keys.yaml has the same "issue" related to the path. Of course the issue for both of the file is that users usually place `theHarvester` directory in different folders, different from `/etc/` or from the directory where `theHarvester.py` is, and since in the code the path is hardcoded, it means that the easiest way is running the tool inside `theHarvester` folder.

I think that there is always a suitable solution: in this case how can we manage this?
In my opinion, for proxies.yaml, I would substitute it by changing the logic of  `-p` like  `-p <protocol>://ip:port`, and delete this file.
The issue should remain on api-keys.yaml. How can we solve it since we still have the following hardcoded path in the code?

```python
@staticmethod
    def api_keys() -> dict:
        try:
            with open('/etc/theHarvester/api-keys.yaml', 'r') as api_keys:
                keys = yaml.safe_load(api_keys)
        except FileNotFoundError:
            try:
                with open('/usr/local/etc/theHarvester/api-keys.yaml', 'r') as api_keys:
                    keys = yaml.safe_load(api_keys)
            except FileNotFoundError:
                with open('api-keys.yaml', 'r') as api_keys:
                    keys = yaml.safe_load(api_keys)
        return keys['apikeys']
```
We must be able to use the parameter of open() function in **dynamic** way, maybe in function of installing directory by setup.py file, or simply take the path of api-keys.yaml by an argument to be inserted by the user when he runs the tool? Is there some other ideas in your side :-\?

**Comment by D3vil0per** [comment] 2021-12-01 22:00
> The error would be due to you needing to import the burp CA cert into your truststore that should fix that error

About this error, I converted the Burpsuite certificate DER file to .crt:

`openssl x509 -inform DER -in /usr/local/share/ca-certificates/cacert.der -out /usr/local/share/ca-certificates/cacert.crt`

then run `sudo update-ca-certificates`

    Updating certificates in /etc/ssl/certs...
    1 added, 0 removed; done.
    Running hooks in /etc/ca-certificates/update.d...

    Adding debian:cacert.pem
    done.
    done.

and I can see `cacert.pem` in `/etc/ssl/certs` but I continue to get the:

    An exception has occurred: Cannot connect to host www.baidu.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')]

**Comment by L1ghtn1ng** [comment] 2023-10-08 19:39
for the api-keys and proxies yaml file this is fixed with the move to pep517 as the backend as it creates the files when theHavester is run and gives you the location of where it is installed in the cli output :-)

**Closed by L1ghtn1ng** 2023-10-08 19:39 UTC
