### ISSUE TITLE
hunterhow's API key is not working..

### ISSUE THREAD

**Issue by kattana12** [laramies/theHarvester#1538] opened 2023-09-12 07:55 UTC

**Comment by NotoriousRebel** [comment] 2023-09-12 18:43
What is the error that occurred?

**Comment by r-wishes** [comment] 2023-09-20 14:19
Hi guys, I think I've just faced the same issue. Even though the hunterhow API key was present in api-keys.yaml along with many others, the following error kept popping up just for this one:
![image](https://github.com/laramies/theHarvester/assets/145533540/ede6dc5a-e5c3-4d6f-bae0-f6672ab13749)

In my case the cause of this error turned out to be a small typo in **theHarvester/lib/core.py** within the **hunterhow_key()** function:
![image](https://github.com/laramies/theHarvester/assets/145533540/64a05289-0918-4bf5-8f65-e88243a4d477)

And the issue can be fixed by correcting the hunterhow key reference:
![image](https://github.com/laramies/theHarvester/assets/145533540/535a7acc-a1fe-4fd4-a553-a6d39db46450)

After this change the error stopped appearing.
Hope it helps.

**Comment by L1ghtn1ng** [comment] 2023-09-20 14:27
Thanks for pointing that out, will fix it after work

On 20 Sep 2023, at 15:19, r-wishes ***@***.***> wrote:

﻿

Hi guys, I think I've just faced the same issue. Even though the hunterhow API key was present in api-keys.yaml along with many others, the following error kept popping up just for this one:
[image]<https://user-images.githubusercontent.com/145533540/269310663-ede6dc5a-e5c3-4d6f-bae0-f6672ab13749.png>

In my case the cause of this error turned out to be a small typo in theHarvester/lib/core.py within the hunterhow_key() function:
[image]<https://user-images.githubusercontent.com/145533540/269311372-64a05289-0918-4bf5-8f65-e88243a4d477.png>

And the issue can be fixed by correcting the hunterhow key reference:
[image]<https://user-images.githubusercontent.com/145533540/269311552-535a7acc-a1fe-4fd4-a553-a6d39db46450.png>

After this change the error stopped appearing.
Hope it helps.

**Comment by kattana12** [comment] 2023-09-21 06:44
Solved...

**Closed** 2023-09-21 06:44 UTC
