### ISSUE TITLE
there's no theharvester on my Kali Linux

### ISSUE THREAD

**Issue by francesco1119** [laramies/theHarvester#24] opened 2015-07-02 19:58 UTC
my Kali is up to date but there is no theharvester.

What to do?

**Comment by darker0n** [comment] 2015-07-04 18:52
Are you sure?
Kali include it

**Comment by francesco1119** [comment] 2015-07-05 07:04
![schermata del 2015-07-05 19 02 24](https://cloud.githubusercontent.com/assets/3397477/8510662/6b1bd678-2348-11e5-86f4-10c4eaeb5ff9.png)
I had to download the master.zip, delete the folder /usr/share/thaharvester (that anyway didn't contained theharvester.py

still just with the command "theharvester" the program doesn't run.

I know that with a simple alias it could work but I wonder how I find myself here

**Comment by laramies** [comment] 2015-07-05 15:32
I've just tried the latest Kali version (1.1.0c) Vmware machine amd64 and I can confirm that theHarvester is there. I am closing this as seems to be a particular issue on your installation.

**Closed by laramies** 2015-07-05 15:32 UTC

**Comment by Nmatt1** [comment] 2017-03-14 18:56
Laramies I am having the same problem with Kali for the Raspberry Pi. It is instrumental that  have this particular piece of software because I need it for a book I am learning from. It is called The Basics Of Hacking And Penetration Testing. How does one fix this issue?

Many thanks 

Nmatt1
