### ISSUE TITLE
It's no longer the tool it once was!

### ISSUE THREAD

**Issue by vincenzogianfelice** [laramies/theHarvester#1554] opened 2023-09-29 15:37 UTC
Debian 12 (x64)

```
An exception has occurred: 400, message='Got more than 8190 bytes (9373) when reading Header value is too long.', url=URL('https://search.brave.com/search?q=%22comunedipastorano.it%22&offset=1&source=web&show_local=0&spellcheck=0')
[*] Searching Hackertarget. 
[*] Searching Rapiddns. 
An exception has occurred: 400, message='Got more than 8190 bytes (9373) when reading Header value is too long.', url=URL('https://search.brave.com/search?q=%22comunedipastorano.it%22&offset=2&source=web&show_local=0&spellcheck=0')
[*] Searching Otx. 
Sitedossier module has triggered a captcha on first iteration, no results can be found.
Change IPs, manually solve the captcha, or wait before rerunning Sitedossier module
[*] Searching Sitedossier. 
[*] Searching Subdomaincenter. 
An exception has occurred: 400, message='Got more than 8190 bytes (9373) when reading Header value is too long.', url=URL('https://search.brave.com/search?q=%22comunedipastorano.it%22&offset=3&source=web&show_local=0&spellcheck=0')
[*] Searching Subdomainfinderc99. 
[*] Searching Urlscan. 
[*] Searching Threatminer. 
An exception has occurred: 400, message='Got more than 8190 bytes (9373) when reading Header value is too long.', url=URL('https://search.brave.com/search?q=%22comunedipastorano.it%22&offset=4&source=web&show_local=0&spellcheck=0')
[*] Searching Yahoo. 
An exception has occurred: 400, message='Got more than 8190 bytes (9373) when reading Header value is too long.', url=URL('https://search.brave.com/search?q=%22comunedipastorano.it%22&offset=5&source=web&show_local=0&spellcheck=0')
```

Ongoing problems

**Comment by L1ghtn1ng** [comment] 2023-09-29 15:40
Closing this as it is a duplicate of #1541 please see that for details.

**Closed** 2023-09-29 15:42 UTC
