### ISSUE TITLE
Fix Disclosing Emails

### ISSUE THREAD

**Issue by phspade** [laramies/theHarvester#59] opened 2017-06-05 10:13 UTC
Hello Team,

Im just wondering if there's a fix to hide emails when using your tool.. so that our email will not disclose to public.

can you suggest a possible mitigation for this?

**Comment by juzsingleton** [comment] 2018-06-02 11:50
theHarvester searches public information.
I would suggest doing the google search manually seeing what sites are displaying your email. Then you can decide whether you want to remove it, ask for it to be removed or live with it.

**Comment by NotoriousRebel** [comment] 2018-12-23 03:54
This is all open source information, the only way to truly prevent this is by making your emails less well known to the public., figure out the root cause.
Closing!

**Closed by NotoriousRebel** 2018-12-23 03:54 UTC
