### ISSUE TITLE
[Bug] Brave error ?

### ISSUE THREAD

**Issue by Rayzen-dev** [laramies/theHarvester#1541] opened 2023-09-18 17:51 UTC
**Feature Request or Bug or Another**
Feature: Bug

**Describe the feature request or bug or other**
When I try to run `python3 theHarvester.py -d exemple.com -b all`, I have an error with brave:
```
An exception has occurred: 400, message='Got more than 8190 bytes (8858) when reading Header value is too long.', url=URL('https://search.brave.com/search?q=%22exemple.com%22&offset=0&source=web&show_local=0&spellcheck=0')
```

**System Information (System that tool is running on):**
 - OS: Parrot OS
 - Version: latest

**Comment by NotoriousRebel** [comment] 2023-09-20 15:12
I'm assuming they changed something in the backend to cause this error, I'll have to debug it this week and figure out the root cause.

**Comment by NotoriousRebel** [comment] 2023-09-24 23:21
After doing some digging this has been a known [bug](https://github.com/aio-libs/aiohttp/issues/2304) in aiohttp that has been talked about for close to 6 years. It looks like a solution has been [implemented and merged](https://github.com/aio-libs/aiohttp/pull/6559). However, it is not yet in the latest version of aiohttp that you can install via pip, so until that is published this error will continue unless brave changes something in the backend to shrink their reply headers. May have to look into patching it in the meantime or hoping the new release comes soon or make a special exception and use requests or httpx temporarily for brave until this gets figured out. There is also an [API for brave search](https://brave.com/search/api/) which may yield more results so that is also another option.

**Comment by Rayzen-dev** [comment] 2023-09-26 18:51
> After doing some digging this has been a known [bug](https://github.com/aio-libs/aiohttp/issues/2304) in aiohttp that has been talked about for close to 6 years. It looks like a solution has been [implemented and merged](https://github.com/aio-libs/aiohttp/pull/6559). However, it is not yet in the latest version of aiohttp that you can install via pip, so until that is published this error will continue unless brave changes something in the backend to shrink their reply headers. May have to look into patching it in the meantime or hoping the new release comes soon or make a special exception and use requests or httpx temporarily for brave until this gets figured out. There is also an [API for brave search](https://brave.com/search/api/) which may yield more results so that is also another option.

Thanks for your reply, I will try soon with this informations.

**Comment by pdblood** [comment] 2023-12-05 15:16
Looks like this is not in aiohttp 3.9.1. Does anyone know what release this fix will appear in?

**Comment by NotoriousRebel** [comment] 2023-12-05 19:18
Did not realize this was fixed, I'll update Brave this weekend.

**Comment by L1ghtn1ng** [comment] 2023-12-18 14:32
fixed in git

**Closed by L1ghtn1ng** 2023-12-18 14:32 UTC
