### ISSUE TITLE
[Bug] setup.py installs /etc/ files in a different location

### ISSUE THREAD

**Issue by blshkv** [laramies/theHarvester#1430] opened 2023-05-21 13:31 UTC
**Bug**
version 4.0.x was working fine. 
The bug was introduced in 4.3.0

```
bash ~ $ theHarvester 
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 106, in proxy_list
    with open('/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/etc/theHarvester/proxies.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 110, in proxy_list
    with open('/usr/local/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/etc/theHarvester/proxies.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/theHarvester", line 5, in <module>
    from theHarvester import __main__
  File "/usr/lib/python3.11/site-packages/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/usr/lib/python3.11/site-packages/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 237, in <module>
    class AsyncFetcher:
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 238, in AsyncFetcher
    proxy_list = Core.proxy_list()
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 113, in proxy_list
    with open('proxies.yaml', 'r') as proxy_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'proxies.yaml'

```
**Describe the feature request or bug or other**
I installed it using setup.py

The location is:
```
equery f theHarvester | grep etc
/usr/lib/python3.11/site-packages/etc
/usr/lib/python3.11/site-packages/etc/theHarvester
/usr/lib/python3.11/site-packages/etc/theHarvester/api-keys.yaml
/usr/lib/python3.11/site-packages/etc/theHarvester/common.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/dns-big.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/dns-names.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/dorks.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/names_small.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/proxies.yaml
```

**To Reproduce**
Steps to reproduce the behaviour:
1. install using setup.py
2. run it

**Expected behaviour**
Developers should not break setup.py because I fixed it once already

**System Information (System that tool is running on):**
 - Pentoo Linux

**Comment by blshkv** [comment] 2023-05-21 13:37
https://github.com/laramies/theHarvester/commit/a6b215e40afaf0fe34bbd3ec3432b04e1092d9b5
this commit broke it. As you can see, "data_files" should have a relative path. It can't be ```etc```

**Comment by L1ghtn1ng** [comment] 2023-05-21 13:40
We have not done anything to the setup.py that would break it. So not sure what is going on here. From first glance it seems to be a pentoo issue, but will look into how to check for any breaks in this process with tests moving forward

On 21 May 2023, at 14:31, Anton Bolshakov ***@***.***> wrote:

﻿

Bug
version 4.2.0 was working fine.
The bug was introduced in 4.30.

bash ~ $ theHarvester
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 106, in proxy_list
    with open('/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/etc/theHarvester/proxies.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 110, in proxy_list
    with open('/usr/local/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/etc/theHarvester/proxies.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/theHarvester", line 5, in <module>
    from theHarvester import __main__
  File "/usr/lib/python3.11/site-packages/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/usr/lib/python3.11/site-packages/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 237, in <module>
    class AsyncFetcher:
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 238, in AsyncFetcher
    proxy_list = Core.proxy_list()
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/theHarvester/lib/core.py", line 113, in proxy_list
    with open('proxies.yaml', 'r') as proxy_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'proxies.yaml'



Describe the feature request or bug or other
I installed it using setup.py

The location is:

equery f theHarvester | grep etc
/usr/lib/python3.11/site-packages/etc
/usr/lib/python3.11/site-packages/etc/theHarvester
/usr/lib/python3.11/site-packages/etc/theHarvester/api-keys.yaml
/usr/lib/python3.11/site-packages/etc/theHarvester/common.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/dns-big.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/dns-names.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/dorks.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/names_small.txt
/usr/lib/python3.11/site-packages/etc/theHarvester/proxies.yaml


To Reproduce
Steps to reproduce the behaviour:

  1.  install using setup.py
  2.  run it

Expected behaviour
Developers should not break setup.py because I fixed it once already

System Information (System that tool is running on):

  *   Pentoo Linux

**Comment by blshkv** [comment] 2023-05-21 13:41
This is what broke it:
```
    data_files=[
        ('share/dict/theHarvester', [
        ('/etc/theHarvester', [
```

**Comment by L1ghtn1ng** [comment] 2023-05-21 13:42
To install things in /etc setup.py  needs to be run with root, then that would work

**Comment by blshkv** [comment] 2023-05-21 13:50
well, I know how to fix it manually. But ideally, a user mode should be supported as well. You can install it for a user like this:

```python setup.py install --user```

**Comment by L1ghtn1ng** [comment] 2023-10-08 18:57
in theory this should be fixed with the move to pep517 that was just merged into master

**Closed by L1ghtn1ng** 2023-10-08 18:57 UTC
