### ISSUE TITLE
[Bug] Proxy does not work

### ISSUE THREAD

**Issue by sssseossss** [laramies/theHarvester#420] opened 2020-04-28 18:18 UTC
**Feature Request or Bug or Other**
Bug 

**Describe the feature request or bug or other**
Proxy does not work. This is the proxies.yaml:
http:
    - 127.0.0.1:8080

I ran burp on the same host listening to the above to see the request as I can google via browser on the same IP, but not getting any results via the tool.

**To Reproduce**
Steps to reproduce the behaviour:
1 run proxy listener
2 setup proxies.yaml as above
3 trigger request by running the tool: python3 theHarvester.py -d example.com -b google -l 100

**Expected behaviour**
expect to see at least IP
[*] Target: example.com
Google is blocking your ip and the workaround, returning
        Searching 0 results.
Google is blocking your ip and the workaround, returning
        Searching 100 results.
[*] Searching Google.
[*] No IPs found.
[*] No emails found.
[*] No hosts found.

**Screenshots**

**System Information (System that tool is running on):**
ubuntu 20.04 LTS + python 3.8 +theHarvester pulled via github today and installed using the nonpipenv method.

Additional Q, if you don't mind - is the user agent "googleUA" or can I customise it anywhere via config? Thanks!

**Comment by NotoriousRebel** [comment] 2020-04-28 18:29
@sssseossss 
1.  You need to tell theHarvester to use proxies by running the tool with -p try that and let me if that fixes your issue.
2. For the google module you would just need to change googleUA here: 
https://github.com/laramies/theHarvester/blob/3c4d66d1313d1a00d4e7bc01a4f3d7a1705618fc/theHarvester/discovery/constants.py#L5

**Comment by sssseossss** [comment] 2020-04-29 08:58
Hi!
thanks for response, however -p parameter did not trigger the use of proxy.

**Comment by NotoriousRebel** [comment] 2020-04-29 17:12
@sssseossss I am pushing a small fix I tested it and was able to intercept traffic with burp

**Comment by L1ghtn1ng** [comment] 2020-05-12 20:25
Timeout and this should now be fixed in master

**Closed by L1ghtn1ng** 2020-05-12 20:25 UTC

**Comment by sssseossss** [comment] 2020-05-14 09:46
hello,
my sincere appologies - I was away for a while, but didn;t meant to raise the issue and dissapear. The proxy worked. Thanks! This will allow me debugging this soft further and I will update you with the findings. Thanks!

**Comment by CatAndCoffee** [comment] 2021-08-03 04:54
I know the key to the problem, the problem is because the script will automatically search for the path. In `theHarvester/lib/core.py`, the script will first search for `/etc/theHarvester/proxies.yaml`, then `/usr/local/etc/theHarvester/proxies.yaml`, and finally `proxies.yaml`. The judgment is whether the file exists or not. If you are using kali,  `/etc/theHarvester/proxies.yaml` will exist in the system by default, and if you do not change this file, the script will not recognize the custom configuration.
